/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const useMessage: typeof import('./src/composables/useMessage')['useMessage']
  const useDownload: typeof import('./src/composables/useDownload')['useDownload']
  const useDict: typeof import('./src/composables/useDict')['useDict']
  const useCommon: typeof import('./src/composables/useCommon')['useCommon']
}